[build]
builder = "nixpacks"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_REQUIREMENTS_FILE = "requirements-minimal.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.env]
NODE_ENV = "production"
