name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-minimal.txt
        pip install pytest pytest-asyncio httpx flake8
    
    - name: Run quick tests
      run: |
        echo "🔍 Running quick validation checks..."
        
        # Check syntax
        python -m py_compile main_simple.py
        
        # Test imports
        python -c "import main_simple; print('✅ Main app imports OK')"
        
        # Quick API test
        python -m pytest tests/test_api.py::test_health_check -v
        
        echo "✅ Pull Request validation passed!"
    
    - name: Comment on PR
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ **Automated Checks Passed!**\n\n- Syntax validation: ✅\n- Import tests: ✅\n- Basic API tests: ✅\n\nThis PR is ready for review!'
          })
